dockerfilesPath: "./dockerfile"

baseBuildConfig:
  conda_build:
    tag: "conda:jupyter"
    dockerfile: "Dockerfile.conda"
    label: "ğŸæ„å»ºCondaé•œåƒ"
    hint: "åŸºäºnvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04é•œåƒï¼ŒåŒ…å«MiniCondaã€JupyterLabã€Openbayesä¸»é¢˜"

  py_build:
    tag: "py:3.10.6-torch2.0.0"
    dockerfile: "Dockerfile.pytorch"
    label: "ğŸ”¥æ„å»ºPytorch2.0é•œåƒ"
    hint: "åŒ…å«Python3.10.6å’ŒPytorch2.0.0"
    dependencies: ["conda_build"]

  sdwebui_base_build:
    tag: "sdwebui_base:rtx4090"
    dockerfile: "Dockerfile.sdwebui_base"
    label: "ğŸ•¹ï¸æ„å»ºStable Diffusion WebUIåŸºæœ¬é•œåƒ"
    dependencies: ["conda_build", "py_build"]

  sdwebui_ext_build:
    tag: "sdwebui_ext:rtx4090"
    dockerfile: "Dockerfile.sdwebui_ext"
    label: "ğŸ§©æ„å»ºStable Diffusion WebUIé™„å¸¦å¸¸ç”¨æ’ä»¶çš„é•œåƒ"
    hint: "åŒ…å«æ±‰åŒ–ã€å›¾åº“æµè§ˆå™¨ã€ControlNetç­‰"
    dependencies: ["conda_build", "py_build", "sdwebui_base_build"]
